# Generated by Django 3.1 on 2023-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0002_auto_20230221_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='sample',
            field=models.FileField(blank=True, null=True, upload_to='book_samples/'),
        ),
    ]
